import { Field, InputType } from '@nestjs/graphql';
import { Customer } from '@modules/customers/entities/customer';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { IOrganizationData } from '@shared/interfaces/organization-data';

@InputType()
export class CreateCustomerInput
  implements Omit<Customer, AutoGeneratedFields | keyof IOrganizationData>
{
  @Field()
  firstName: string;

  @Field()
  lastName: string;

  @Field()
  email: string;

  @Field()
  password: string;

  @Field()
  phone: string;
}
