import { Field, InputType } from '@nestjs/graphql';
import { Customer } from '@modules/customers/entities/customer';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { IsEmail, IsPhoneNumber, IsString, Validate } from 'class-validator';
import { IsObjectId } from '@shared/validations/is-object-id';

@InputType()
export class CreateCustomerInput
  implements Omit<Customer, AutoGeneratedFields>
{
  @Field()
  @Validate(IsObjectId)
  organizationId: string;

  @Field()
  @IsString()
  firstName: string;

  @Field()
  @IsString()
  lastName: string;

  @Field()
  @IsEmail()
  email: string;

  @Field()
  @IsString()
  password: string;

  @Field()
  @IsPhoneNumber('BR')
  phone: string;
}
