import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { toObjectId } from '@shared/utils/to-object-id';
import { Complement, ComplementDocument } from '../entities/complement';

type ScopeParams = {
  organizationId: string;
  locationId: string;
};

type FindOneParams = ScopeParams & { _id: string };

@Injectable()
export class ComplementDataSource {
  constructor(
    @InjectModel(Complement.name)
    private readonly complementModel: Model<ComplementDocument>,
  ) {}

  async createOne(
    payload: Omit<Complement, AutoGeneratedFields>,
  ): Promise<Complement> {
    const result = await this.complementModel.create(payload);
    return result.toObject();
  }

  async findById(params: FindOneParams): Promise<Complement | null> {
    const result = await this.complementModel.findOne(params);
    return result?.toObject() ?? null;
  }

  async findByIds(
    ids: string[],
    params: ScopeParams,
  ): Promise<Complement[]> {
    if (ids.length === 0) return [];

    const result = await this.complementModel.find({
      ...params,
      _id: { $in: ids.map(toObjectId) },
    });

    return result.map((item) => item.toObject());
  }

  async listByGroup(
    complementGroupId: string,
    params: ScopeParams,
  ): Promise<Complement[]> {
    const result = await this.complementModel
      .find({ ...params, complementGroupId })
      .sort({ displayOrder: 1, name: 1 });

    return result.map((item) => item.toObject());
  }

  async listByGroupIds(
    complementGroupIds: string[],
    params: ScopeParams,
  ): Promise<Complement[]> {
    if (complementGroupIds.length === 0) return [];

    const result = await this.complementModel
      .find({
        ...params,
        complementGroupId: { $in: complementGroupIds },
      })
      .sort({ displayOrder: 1, name: 1 });

    return result.map((item) => item.toObject());
  }

  async updateOne(
    params: FindOneParams,
    data: Partial<Complement>,
  ): Promise<Complement | null> {
    const result = await this.complementModel.findOneAndUpdate(params, data, {
      new: true,
    });

    return result?.toObject() ?? null;
  }
}
