import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { toObjectId } from '@shared/utils/to-object-id';
import {
  ComplementGroup,
  ComplementGroupDocument,
} from '../entities/complement-group';

type ScopeParams = {
  organizationId: string;
  locationId: string;
};

type FindOneParams = ScopeParams & { _id: string };

@Injectable()
export class ComplementGroupDataSource {
  constructor(
    @InjectModel(ComplementGroup.name)
    private readonly complementGroupModel: Model<ComplementGroupDocument>,
  ) {}

  async createOne(
    payload: Omit<ComplementGroup, AutoGeneratedFields>,
  ): Promise<ComplementGroup> {
    const result = await this.complementGroupModel.create(payload);
    return result.toObject();
  }

  async findById(params: FindOneParams): Promise<ComplementGroup | null> {
    const result = await this.complementGroupModel.findOne(params);
    return result?.toObject() ?? null;
  }

  async findByIds(
    ids: string[],
    params: ScopeParams,
  ): Promise<ComplementGroup[]> {
    if (ids.length === 0) return [];

    const result = await this.complementGroupModel.find({
      ...params,
      _id: { $in: ids.map(toObjectId) },
    });

    return result.map((item) => item.toObject());
  }

  async listByLocation(params: ScopeParams): Promise<ComplementGroup[]> {
    const result = await this.complementGroupModel
      .find(params)
      .sort({ name: 1 });

    return result.map((item) => item.toObject());
  }

  async updateOne(
    params: FindOneParams,
    data: Partial<ComplementGroup>,
  ): Promise<ComplementGroup | null> {
    const result = await this.complementGroupModel.findOneAndUpdate(
      params,
      data,
      { new: true },
    );

    return result?.toObject() ?? null;
  }
}
