import { Field, InputType } from '@nestjs/graphql';
import {
  IsArray,
  IsBoolean,
  IsNumber,
  IsOptional,
  IsString,
} from 'class-validator';
import { Product } from '@modules/products/entities/product';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';

@InputType()
export class CreateProductInput
  implements Omit<Product, AutoGeneratedFields | 'organizationId'>
{
  @Field()
  @IsString()
  name: string;

  @IsString()
  @IsOptional()
  @Field({ nullable: true })
  description?: string;

  @Field()
  @IsBoolean()
  isActive: boolean;

  @Field()
  @IsNumber()
  originalPrice: number;

  @IsNumber()
  @IsOptional()
  @Field({ nullable: true })
  promotionalPrice?: number;

  @IsBoolean()
  @IsOptional()
  @Field({ nullable: true })
  isPromotionalPriceEnabled?: boolean;

  @IsArray()
  @IsOptional()
  @Field({ nullable: true })
  categoryId?: string;
}
