import { Field, InputType } from '@nestjs/graphql';
import {
  IsArray,
  IsBoolean,
  IsNumber,
  IsOptional,
  IsString,
  IsUrl,
} from 'class-validator';
import { Product } from '@modules/products/entities/product';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { Type } from 'class-transformer';
import { ProductComplementGroupInput } from './product-complement-group.dto';

@InputType()
export class ProductImageInput {
  // @IsInt()
  // @IsOptional()
  // index?: number;

  @IsUrl()
  @Field()
  url: string;
}

@InputType()
export class CreateProductInput
  implements Omit<Product, AutoGeneratedFields | 'images' | 'complementGroups'>
{
  organizationId: string;

  locationId: string;

  @IsString()
  @IsOptional()
  @Field({ nullable: true })
  identifier?: string;

  @Field()
  @IsString()
  name: string;

  @IsString()
  @IsOptional()
  @Field({ nullable: true })
  description?: string;

  @Field()
  @IsBoolean()
  isActive: boolean;

  @Field()
  @IsNumber()
  originalPrice: number;

  @IsNumber()
  @IsOptional()
  @Field({ nullable: true })
  promotionalPrice?: number;

  @IsBoolean()
  @IsOptional()
  @Field({ nullable: true })
  isPromotionalPriceEnabled?: boolean;

  @IsOptional()
  @IsArray({ each: true })
  @Type(() => ProductImageInput)
  @Field(() => [ProductImageInput], { nullable: true })
  images: ProductImageInput[];

  @IsArray()
  @IsOptional()
  @Type(() => ProductComplementGroupInput)
  @Field(() => [ProductComplementGroupInput], { nullable: true })
  complementGroups?: ProductComplementGroupInput[];
}
