import { Field, InputType } from '@nestjs/graphql';
import { Product } from '@modules/products/entities/product';
import {
  IsArray,
  IsBoolean,
  IsNumber,
  IsOptional,
  IsString,
  Validate,
} from 'class-validator';
import { IsObjectId } from '@shared/validations/is-object-id';
import { ProductImageInput } from './create-product.input';
import { Type } from 'class-transformer';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';

@InputType()
export class UpdateProductInput
  implements Partial<Omit<Product, AutoGeneratedFields | 'images'>>
{
  @Field()
  @Validate(IsObjectId)
  _id: string;

  organizationId: string;

  locationId: string;

  @IsString()
  @IsOptional()
  @Field({ nullable: true })
  identifier?: string;

  @IsOptional()
  @IsArray()
  @Type(() => ProductImageInput)
  @Field(() => [ProductImageInput], { nullable: true })
  images: ProductImageInput[];

  @Field({ nullable: true })
  @IsString()
  @IsOptional()
  name?: string;

  @Field({ nullable: true })
  @IsString()
  @IsNumber({ maxDecimalPlaces: 2 })
  @IsOptional()
  originalPrice?: number;

  @Field({ nullable: true })
  @IsNumber({ maxDecimalPlaces: 2 })
  @IsOptional()
  promotionalPrice?: number;

  @Field({ nullable: true })
  @IsString()
  @IsOptional()
  description?: string;

  @Field({ nullable: true })
  @IsBoolean()
  @IsOptional()
  isActive?: boolean;

  @Field({ nullable: true })
  @IsBoolean()
  @IsOptional()
  isPromotionalPriceEnabled?: boolean;
}
