import { Model } from 'mongoose';
import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Menu } from '../entities/menu';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';

interface IMenuDataSource {
  getByOrganization(organizationId: string): Promise<Menu[]>;
  create(data: Omit<Menu, AutoGeneratedFields>): Promise<Menu>;
}

@Injectable()
export class MenuDataSource implements IMenuDataSource {
  constructor(
    @InjectModel(Menu.name)
    private menuModel: Model<Menu>,
  ) {}

  async getByOrganization(organizationId: string): Promise<Menu[]> {
    return this.menuModel.find({ organizationId });
  }

  async create(data: Omit<Menu, AutoGeneratedFields>): Promise<Menu> {
    const result = await this.menuModel.create(data);
    return result.toObject();
  }

  // get com os produtos e categorias
}
