import { Category } from '@modules/categories/entities/category';
import { Field, InputType } from '@nestjs/graphql';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { IsString } from 'class-validator';

@InputType()
export class CreateCategoryInput
  implements Omit<Category, AutoGeneratedFields | 'organizationId'>
{
  @Field()
  @IsString()
  name: string;

  @IsString()
  @Field({ nullable: true })
  description?: string;
}
