import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { FilterQuery, Model } from 'mongoose';
import {
  LocationShift,
  LocationShiftDocument,
} from '../entities/location-shift';
import { LocationShiftStatuses } from '../enums/location-shift-statuses';
import { buildOpenLocationShiftFilter } from '../utils/location-shift-open.utils';

export type ListLocationShiftsFilters = {
  limit: number;
  offset: number;
  startedAtFrom?: Date;
  startedAtTo?: Date;
  finishedAtFrom?: Date;
  finishedAtTo?: Date;
};

interface ILocationShiftDataSource {
  createOne(
    data: Omit<LocationShift, AutoGeneratedFields>,
  ): Promise<LocationShift>;
  findById(id: string, organizationId: string): Promise<LocationShift | null>;
  findOpenByLocation(
    organizationId: string,
    locationId: string,
  ): Promise<LocationShift | null>;
  closeOne(
    id: string,
    organizationId: string,
    finishedAt: Date,
  ): Promise<boolean>;
  incrementTableOrderQuantity(
    id: string,
    organizationId: string,
  ): Promise<boolean>;
  incrementOrderTabsQuantity(
    id: string,
    organizationId: string,
  ): Promise<boolean>;
  listByLocationAndFilters(
    organizationId: string,
    locationId: string,
    filters: ListLocationShiftsFilters,
  ): Promise<{ shifts: LocationShift[]; totalCount: number }>;
}

@Injectable()
export class LocationShiftDataSource implements ILocationShiftDataSource {
  constructor(
    @InjectModel(LocationShift.name)
    private locationShiftModel: Model<LocationShiftDocument>,
  ) {}

  async createOne(
    data: Omit<LocationShift, AutoGeneratedFields>,
  ): Promise<LocationShift> {
    const shift = await this.locationShiftModel.create(data);
    return shift.toObject();
  }

  async findById(
    id: string,
    organizationId: string,
  ): Promise<LocationShift | null> {
    const shift = await this.locationShiftModel.findOne({
      _id: id,
      organizationId,
    });

    return shift?.toObject() ?? null;
  }

  async findOpenByLocation(
    organizationId: string,
    locationId: string,
  ): Promise<LocationShift | null> {
    const shift = await this.locationShiftModel.findOne(
      buildOpenLocationShiftFilter(organizationId, locationId),
    );

    return shift?.toObject() ?? null;
  }

  async closeOne(
    id: string,
    organizationId: string,
    finishedAt: Date,
  ): Promise<boolean> {
    const result = await this.locationShiftModel.updateOne(
      { _id: id, organizationId },
      {
        $set: {
          status: LocationShiftStatuses.CLOSED,
          finishedAt,
        },
      },
    );

    return result.matchedCount > 0;
  }

  async incrementTableOrderQuantity(
    id: string,
    organizationId: string,
  ): Promise<boolean> {
    const result = await this.locationShiftModel.updateOne(
      { _id: id, organizationId },
      { $inc: { currentTableOrderQuantity: 1 } },
    );

    return result.matchedCount > 0;
  }

  async incrementOrderTabsQuantity(
    id: string,
    organizationId: string,
  ): Promise<boolean> {
    const result = await this.locationShiftModel.updateOne(
      { _id: id, organizationId },
      { $inc: { currentOrderTabsQuantity: 1 } },
    );

    return result.matchedCount > 0;
  }

  async listByLocationAndFilters(
    organizationId: string,
    locationId: string,
    filters: ListLocationShiftsFilters,
  ): Promise<{ shifts: LocationShift[]; totalCount: number }> {
    const query: FilterQuery<LocationShiftDocument> = {
      organizationId,
      locationId,
    };

    if (filters.startedAtFrom || filters.startedAtTo) {
      query.startedAt = {};
      if (filters.startedAtFrom) query.startedAt.$gte = filters.startedAtFrom;
      if (filters.startedAtTo) query.startedAt.$lte = filters.startedAtTo;
    }

    if (filters.finishedAtFrom || filters.finishedAtTo) {
      query.finishedAt = {};
      if (filters.finishedAtFrom) {
        query.finishedAt.$gte = filters.finishedAtFrom;
      }
      if (filters.finishedAtTo) {
        query.finishedAt.$lte = filters.finishedAtTo;
      }
    }

    const [shifts, totalCount] = await Promise.all([
      this.locationShiftModel
        .find(query, {}, { skip: filters.offset, limit: filters.limit })
        .sort({ startedAt: -1 }),
      this.locationShiftModel.countDocuments(query),
    ]);

    return {
      shifts: shifts.map((shift) => shift.toObject()),
      totalCount,
    };
  }
}
