import { Table } from '@modules/table/entities/table';
import { Field, InputType } from '@nestjs/graphql';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';

@InputType()
export class CreateTableInput implements Omit<Table, AutoGeneratedFields> {
  @Field()
  organizationId: string;

  @Field()
  locationId: string;

  @Field()
  identifier: string;
}
