import { TokenData } from '@modules/auth/services/token.service';
import { Table } from '@modules/table/entities/table';
import { Field, InputType } from '@nestjs/graphql';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { IsString } from 'class-validator';

@InputType()
export class CreateTableInput
  implements Omit<Table, AutoGeneratedFields | keyof TokenData>
{
  @Field()
  @IsString()
  identifier: string;
}
