import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Organization, OrganizationDocument } from '../entities/organization';

type AutoGeneratedOrgFields = '_id' | 'createdAt' | 'updatedAt';

interface IOrganizationDataSource {
  createOne(
    input: Omit<Organization, AutoGeneratedOrgFields>,
  ): Promise<Organization>;
}

@Injectable()
export class OrganizationDataSource implements IOrganizationDataSource {
  constructor(
    @InjectModel(Organization.name)
    private readonly orgModel: Model<OrganizationDocument>,
  ) {}

  async createOne(
    input: Omit<Organization, AutoGeneratedOrgFields>,
  ): Promise<Organization> {
    return this.orgModel.create(input);
  }
}
