// Template: datasources/__entityName__.datasource.ts
// Adaptar: nomes de tipo, campos de filtro, e adicionar métodos extras conforme
// novos usecases forem chegando (via skill new-usecase) — não precisa antecipar
// métodos que nenhum usecase usa ainda (ISP).
import { Model } from 'mongoose';
import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { IPaginationOptions } from '@shared/interfaces/pagination-options';
import {
  __EntityName__,
  __EntityName__Document,
} from '../entities/__entityName__';

type FilterParams = {
  organizationId: string;
  locationId?: string;
};

type FindOneParams = {
  _id: string;
} & FilterParams;

interface I__EntityName__DataSource {
  findById(params: FindOneParams): Promise<__EntityName__ | null>;
  createOne(
    payload: Omit<__EntityName__, AutoGeneratedFields>,
  ): Promise<__EntityName__>;
  listByOrganization(
    params: FilterParams,
    paginationOptions: IPaginationOptions,
  ): Promise<__EntityName__[]>;
  updateOne(id: string, data: Partial<__EntityName__>): Promise<boolean>;
}

@Injectable()
export class __EntityName__DataSource implements I__EntityName__DataSource {
  constructor(
    @InjectModel(__EntityName__.name)
    private __entityName__Model: Model<__EntityName__Document>,
  ) {}

  async findById(params: FindOneParams): Promise<__EntityName__ | null> {
    const result = await this.__entityName__Model.findOne(params);
    return result?.toObject();
  }

  async createOne(
    payload: Omit<__EntityName__, AutoGeneratedFields>,
  ): Promise<__EntityName__> {
    const result = await this.__entityName__Model.create(payload);
    return result.toObject();
  }

  async listByOrganization(
    params: FilterParams,
    paginationOptions: IPaginationOptions,
  ): Promise<__EntityName__[]> {
    const result = await this.__entityName__Model.find(
      params,
      {},
      { skip: paginationOptions.offset, limit: paginationOptions.limit },
    );

    return result.map((item) => item.toObject());
  }

  async updateOne(id: string, data: Partial<__EntityName__>): Promise<boolean> {
    const result = await this.__entityName__Model.updateOne(
      { _id: id },
      data,
    );

    return result.modifiedCount > 0;
  }
}
