// Template: usecases/dto/create-__entity-name__.input.ts
// Adaptar campos para os da entidade (menos os automáticos: _id/createdAt/updatedAt).
// organizationId/locationId não levam @Field() aqui porque vêm do @CurrentUser(),
// não do input do cliente (ver resolver.template.ts: `{ ...input, ...user }`).
import { Field, InputType } from '@nestjs/graphql';
import { IsBoolean, IsOptional, IsString } from 'class-validator';
import { __EntityName__ } from '@modules/__module-folder__/entities/__entityName__';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';

@InputType()
export class Create__EntityName__Input
  implements Omit<__EntityName__, AutoGeneratedFields | 'isActive'>
{
  organizationId: string;

  locationId: string;

  @Field({ nullable: true })
  @IsBoolean()
  @IsOptional()
  isActive?: boolean;

  @Field()
  @IsString()
  name: string;
}
