import { Category } from '@modules/categories/entities/category';
import { Field, InputType } from '@nestjs/graphql';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { IsObjectId } from '@shared/validations/is-object-id';
import {
  IsArray,
  IsBoolean,
  IsOptional,
  IsString,
  Validate,
} from 'class-validator';

@InputType()
export class CreateCategoryInput
  implements Omit<Category, AutoGeneratedFields | 'productIds' | 'isActive'>
{
  organizationId: string;

  locationId: string;

  @Field({ nullable: true })
  @IsBoolean()
  isActive?: boolean;

  @Field()
  @IsString()
  name: string;

  @IsString()
  @IsOptional()
  @Field({ nullable: true })
  description?: string;

  @IsArray()
  @IsOptional()
  @Field(() => [String], { nullable: true })
  @Validate(IsObjectId, { each: true })
  productIds?: string[];
}
