import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { PrintJob, PrintJobDocument } from '../entities/print-job';
import { PrintJobStatus } from '../enums/print-job-status';

export type ListPrintJobsFilters = {
  status?: PrintJobStatus;
  limit: number;
  offset: number;
};

@Injectable()
export class PrintJobDataSource {
  constructor(
    @InjectModel(PrintJob.name)
    private printJobModel: Model<PrintJobDocument>,
  ) {}

  async createOne(
    data: Omit<PrintJob, AutoGeneratedFields>,
  ): Promise<PrintJob | null> {
    try {
      const job = await this.printJobModel.create(data);
      return job.toObject();
    } catch (error: unknown) {
      const mongoError = error as { code?: number };
      if (mongoError.code === 11000) {
        return this.findByIdempotencyKey(data.idempotencyKey);
      }
      throw error;
    }
  }

  async findById(
    id: string,
    organizationId: string,
  ): Promise<PrintJob | null> {
    return this.printJobModel
      .findOne({ _id: id, organizationId })
      .lean()
      .exec();
  }

  async findByIdempotencyKey(
    idempotencyKey: string,
  ): Promise<PrintJob | null> {
    return this.printJobModel.findOne({ idempotencyKey }).lean().exec();
  }

  async listByLocation(
    organizationId: string,
    locationId: string,
    filters: ListPrintJobsFilters,
  ): Promise<{ jobs: PrintJob[]; totalCount: number }> {
    const query: Record<string, unknown> = { organizationId, locationId };

    if (filters.status) {
      query.status = filters.status;
    }

    const [jobs, totalCount] = await Promise.all([
      this.printJobModel
        .find(query)
        .sort({ createdAt: -1 })
        .skip(filters.offset)
        .limit(filters.limit)
        .lean()
        .exec(),
      this.printJobModel.countDocuments(query).exec(),
    ]);

    return { jobs, totalCount };
  }

  async updateStatus(
    id: string,
    organizationId: string,
    data: {
      status: PrintJobStatus;
      errorMessage?: string;
      printedAt?: Date;
      assignedAgentId?: string;
    },
  ): Promise<PrintJob | null> {
    return this.printJobModel
      .findOneAndUpdate({ _id: id, organizationId }, data, { new: true })
      .lean()
      .exec();
  }
}
