import { Model } from 'mongoose';
import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import {
  Invitation,
  InvitationDocument,
  InvitationStatus,
} from '../entities/invitation';

interface IInvitationDataSource {
  createOne(data: Omit<Invitation, AutoGeneratedFields>): Promise<Invitation>;
  findById(id: string, organizationId: string): Promise<Invitation | null>;
  findByToken(token: string): Promise<Invitation | null>;
  findPendingByOrgAndEmail(
    organizationId: string,
    email: string,
  ): Promise<Invitation | null>;
  listByOrganization(
    organizationId: string,
    status: InvitationStatus,
  ): Promise<Invitation[]>;
  updateOne(id: string, data: Partial<Invitation>): Promise<Invitation>;
}

@Injectable()
export class InvitationDataSource implements IInvitationDataSource {
  constructor(
    @InjectModel(Invitation.name)
    private readonly invitationModel: Model<InvitationDocument>,
  ) {}

  async createOne(
    data: Omit<Invitation, AutoGeneratedFields>,
  ): Promise<Invitation> {
    const invitation = await this.invitationModel.create(data);
    return invitation.toObject();
  }

  async findById(
    id: string,
    organizationId: string,
  ): Promise<Invitation | null> {
    const invitation = await this.invitationModel.findOne({
      _id: id,
      organizationId,
    });

    return invitation?.toObject() ?? null;
  }

  async findByToken(token: string): Promise<Invitation | null> {
    const invitation = await this.invitationModel.findOne({ token });
    return invitation?.toObject() ?? null;
  }

  async findPendingByOrgAndEmail(
    organizationId: string,
    email: string,
  ): Promise<Invitation | null> {
    const invitation = await this.invitationModel.findOne({
      organizationId,
      email,
      status: InvitationStatus.PENDING,
    });

    return invitation?.toObject() ?? null;
  }

  async listByOrganization(
    organizationId: string,
    status: InvitationStatus,
  ): Promise<Invitation[]> {
    const invitations = await this.invitationModel
      .find({ organizationId, status })
      .sort({ createdAt: -1 });

    return invitations.map((invitation) => invitation.toObject());
  }

  async updateOne(id: string, data: Partial<Invitation>): Promise<Invitation> {
    return this.invitationModel.findByIdAndUpdate(id, data, { new: true });
  }
}
