import { FilterQuery, Model } from 'mongoose';
import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { OrganizationRole } from '../enums/organization-role';
import { User, UserDocument } from '../entities/user';

export type FindManyByOrganizationParams = {
  search?: string;
  page?: number;
  limit?: number;
};

export type FindManyByOrganizationResult = {
  data: User[];
  hasNextPage: boolean;
};

export interface IUserDataSource {
  findById(userId: string): Promise<User | null>;
  findByEmail(
    email: string,
    params?: { returnPassword: boolean },
  ): Promise<User | null>;
  createOne(data: Omit<User, AutoGeneratedFields>): Promise<User>;
  updateOne(userId: string, payload: Partial<User>): Promise<User>;
  findManyByOrganization(
    organizationId: string,
    params: FindManyByOrganizationParams,
  ): Promise<FindManyByOrganizationResult>;
  countByOrganizationAndRole(
    organizationId: string,
    role: OrganizationRole,
  ): Promise<number>;
  updateRoles(
    userId: string,
    organizationId: string,
    roles: OrganizationRole[],
  ): Promise<User | null>;
}

@Injectable()
export class UserDataSource implements IUserDataSource {
  constructor(
    @InjectModel(User.name)
    private readonly userModel: Model<UserDocument>,
  ) {}

  async findById(userId: string): Promise<User | null> {
    return this.userModel.findById(userId);
  }

  async findByEmail(
    email: string,
    params: { returnPassword: boolean } = { returnPassword: false },
  ): Promise<User | null> {
    const user = await this.userModel.findOne({ email });

    const result = user ? user.toObject() : null;

    if (result && !params.returnPassword) {
      result.password = undefined;
    }

    return result;
  }

  async createOne(data: Omit<User, AutoGeneratedFields>): Promise<User> {
    const user = await this.userModel.create(data);
    return user.toObject();
  }

  async updateOne(userId: string, payload: Partial<User>): Promise<User> {
    return this.userModel.findOneAndUpdate({ _id: userId }, payload, {
      new: true,
    });
  }

  async findManyByOrganization(
    organizationId: string,
    { search, page = 1, limit = 20 }: FindManyByOrganizationParams,
  ): Promise<FindManyByOrganizationResult> {
    const filter: FilterQuery<UserDocument> = { organizationId };

    if (search) {
      const regex = new RegExp(search, 'i');
      filter.$or = [
        { firstName: regex },
        { lastName: regex },
        { email: regex },
      ];
    }

    const skip = (page - 1) * limit;

    const results = await this.userModel
      .find(filter)
      .skip(skip)
      .limit(limit + 1);

    const hasNextPage = results.length > limit;

    return {
      data: results.slice(0, limit).map((user) => user.toObject()),
      hasNextPage,
    };
  }

  async countByOrganizationAndRole(
    organizationId: string,
    role: OrganizationRole,
  ): Promise<number> {
    return this.userModel.countDocuments({ organizationId, roles: role });
  }

  async updateRoles(
    userId: string,
    organizationId: string,
    roles: OrganizationRole[],
  ): Promise<User | null> {
    return this.userModel.findOneAndUpdate(
      { _id: userId, organizationId },
      { roles },
      { new: true },
    );
  }
}
