import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { DeepPartial } from '@shared/utils/deep-partial';
import { OrderTab, OrderTabDocument } from '../entities/order-tab';
import { TableOrderItem } from '../entities/table-order-item';

interface IOrderTabDataSource {
  createOne(data: Omit<OrderTab, AutoGeneratedFields>): Promise<OrderTab>;
  findById(id: string, organizationId: string): Promise<OrderTab | null>;
  findByTableOrderId(
    tableOrderId: string,
    organizationId: string,
  ): Promise<OrderTab[]>;
  updateOne(
    id: string,
    organizationId: string,
    data: DeepPartial<OrderTab>,
  ): Promise<boolean>;
  pushItem(orderTabId: string, item: Partial<TableOrderItem>): Promise<boolean>;
  updateItem(
    orderTabId: string,
    itemId: string,
    data: Partial<TableOrderItem>,
  ): Promise<boolean>;
  removeItem(orderTabId: string, itemId: string): Promise<boolean>;
}

@Injectable()
export class OrderTabDataSource implements IOrderTabDataSource {
  constructor(
    @InjectModel(OrderTab.name)
    private orderTabModel: Model<OrderTabDocument>,
  ) {}

  async createOne(
    data: Omit<OrderTab, AutoGeneratedFields>,
  ): Promise<OrderTab> {
    const orderTab = await this.orderTabModel.create(data);
    return orderTab.toObject();
  }

  async findById(
    id: string,
    organizationId: string,
  ): Promise<OrderTab | null> {
    const orderTab = await this.orderTabModel.findOne({
      _id: id,
      organizationId,
    });

    if (!orderTab) return null;

    return orderTab.toObject();
  }

  async findByTableOrderId(
    tableOrderId: string,
    organizationId: string,
  ): Promise<OrderTab[]> {
    const tabs = await this.orderTabModel
      .find({ tableOrderId, organizationId })
      .sort({ sequence: 1 });

    return tabs.map((tab) => tab.toObject());
  }

  async updateOne(
    id: string,
    organizationId: string,
    data: DeepPartial<OrderTab>,
  ): Promise<boolean> {
    const result = await this.orderTabModel.updateOne(
      { _id: id, organizationId },
      data,
    );

    return result.matchedCount > 0;
  }

  async pushItem(
    orderTabId: string,
    item: Partial<TableOrderItem>,
  ): Promise<boolean> {
    const result = await this.orderTabModel.updateOne(
      { _id: orderTabId },
      { $push: { items: item } },
    );

    return result.matchedCount > 0;
  }

  async updateItem(
    orderTabId: string,
    itemId: string,
    data: Partial<TableOrderItem>,
  ): Promise<boolean> {
    const setData = {};
    Object.keys(data).forEach((key) => {
      setData[`items.$.${key}`] = data[key];
    });

    const result = await this.orderTabModel.updateOne(
      {
        _id: orderTabId,
        'items._id': itemId,
      },
      {
        $set: setData,
      },
    );

    return result.matchedCount > 0;
  }

  async removeItem(orderTabId: string, itemId: string): Promise<boolean> {
    const result = await this.orderTabModel.updateOne(
      { _id: orderTabId },
      {
        $pull: {
          items: { _id: itemId },
        },
      },
    );

    return result.matchedCount > 0;
  }
}
