import { Model } from 'mongoose';
import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { TableOrder, TableOrderDocument } from '../entities/table-order';

interface ITableOrderDataSource {
  createOne(data: Omit<TableOrder, AutoGeneratedFields>): Promise<TableOrder>;
}

@Injectable()
export class TableOrderDataSource implements ITableOrderDataSource {
  constructor(
    @InjectModel(TableOrder.name)
    private tableOrderModel: Model<TableOrderDocument>,
  ) {}

  async createOne(
    data: Omit<TableOrder, AutoGeneratedFields>,
  ): Promise<TableOrder> {
    const order = await this.tableOrderModel.create(data);
    return order.toObject();
  }
}
