import { Model } from 'mongoose';
import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { Table, TableDocument } from '../entities/table';
import {
  TableOrder,
  TableOrderDocument,
} from '@modules/table-orders/entities/table-order';
import { TableOrderStatuses } from '@modules/table-orders/enums/table-order-statuses';

interface ITableDataSource {
  getByOrgAndLocationIds(
    organizationId: string,
    locationId: string,
  ): Promise<Table[]>;
  listAvailableByOrgAndLocationIds(
    organizationId: string,
    locationId: string,
  ): Promise<Table[]>;
  findById(tableId: string): Promise<Table | null>;
  findByTableAndOrgId(
    tableId: string,
    organizationId: string,
  ): Promise<Table | null>;
  createOne(payload: Omit<Table, AutoGeneratedFields>): Promise<Table>;
  updateOne(
    tableId: string,
    organizationId: string,
    locationId: string,
    payload: Partial<Table>,
  ): Promise<Table | null>;
  deleteOne(
    tableId: string,
    organizationId: string,
    locationId: string,
  ): Promise<Table | null>;
}

@Injectable()
export class TableDataSource implements ITableDataSource {
  constructor(
    @InjectModel(Table.name)
    private readonly tableModel: Model<TableDocument>,
    @InjectModel(TableOrder.name)
    private readonly tableOrderModel: Model<TableOrderDocument>,
  ) {}

  async getByOrgAndLocationIds(
    organizationId: string,
    locationId: string,
  ): Promise<Table[]> {
    return this.tableModel.find({ organizationId, locationId });
  }

  async listAvailableByOrgAndLocationIds(
    organizationId: string,
    locationId: string,
  ): Promise<Table[]> {
    const occupiedTableIds = await this.tableOrderModel.distinct(
      'table._id',
      {
        organizationId,
        locationId,
        status: TableOrderStatuses.IN_ATTENDANCE,
      },
    );

    return this.tableModel.find({
      organizationId,
      locationId,
      _id: { $nin: occupiedTableIds },
    });
  }

  async findByTableAndOrgId(
    tableId: string,
    organizationId: string,
  ): Promise<Table> {
    return this.tableModel.findOne({
      _id: tableId,
      organizationId,
    });
  }

  async findById(tableId: string): Promise<Table> {
    return this.tableModel.findById(tableId);
  }

  async createOne(payload: Omit<Table, AutoGeneratedFields>): Promise<Table> {
    const result = await this.tableModel.create(payload);
    return result.toObject();
  }

  async updateOne(
    tableId: string,
    organizationId: string,
    locationId: string,
    payload: Partial<Table>,
  ): Promise<Table | null> {
    const result = await this.tableModel.findOneAndUpdate(
      { _id: tableId, organizationId, locationId },
      payload,
      { new: true },
    );

    return result?.toObject() ?? null;
  }

  async deleteOne(
    tableId: string,
    organizationId: string,
    locationId: string,
  ): Promise<Table | null> {
    const result = await this.tableModel.findOneAndDelete({
      _id: tableId,
      organizationId,
      locationId,
    });

    return result?.toObject() ?? null;
  }
}
