import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Table, TableDocument } from '../entities/table';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';

interface ITableDataSource {
  createOne(payload: Omit<Table, AutoGeneratedFields>): Promise<Table>;
}

@Injectable()
export class TableDataSource implements ITableDataSource {
  constructor(
    @InjectModel(Table.name)
    private readonly tableModel: Model<TableDocument>,
  ) {}

  async createOne(payload: Omit<Table, AutoGeneratedFields>): Promise<Table> {
    const result = await this.tableModel.create(payload);
    return result.toObject();
  }
}
