import { Model } from 'mongoose';
import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { TableOrder, TableOrderDocument } from '../entities/table-order';
import {
  OrderOptions,
  IPaginationOptions,
} from '@shared/interfaces/pagination-options';
import { TableOrderStatuses } from '../enums/table-order-statuses';
import { TableOrderItem } from '../entities/table-order-item';

interface IListTableOrdersFilters extends IPaginationOptions {
  status?: TableOrderStatuses;
  creationDate?: OrderOptions;
}

interface ITableOrderDataSource {
  createOne(data: Omit<TableOrder, AutoGeneratedFields>): Promise<TableOrder>;
  findByLocationAndId(
    locationId: string,
    tableOrderId: string,
  ): Promise<TableOrder | null>;
  listByLocationAndFilters(
    locationId: string,
    filters: IListTableOrdersFilters,
  ): Promise<TableOrder[]>;
  updateOne(
    tableOrderId: string,
    data: Partial<TableOrder>,
  ): Promise<TableOrder>;
}

@Injectable()
export class TableOrderDataSource implements ITableOrderDataSource {
  constructor(
    @InjectModel(TableOrder.name)
    private tableOrderModel: Model<TableOrderDocument>,
  ) {}

  async listByLocationAndFilters(
    locationId: string,
    filters: IListTableOrdersFilters,
  ): Promise<TableOrder[]> {
    const query: Partial<TableOrder> = {
      locationId,
    };

    if (filters.status) query.status = filters.status;

    const filteredOrders = await this.tableOrderModel
      .find(query, {}, { skip: filters.offset, limit: filters.limit })
      .sort({ createdAt: filters.creationDate });

    return filteredOrders.map((item) => item.toObject());
  }

  async findByLocationAndId(
    locationId: string,
    tableOrderId: string,
  ): Promise<TableOrder> {
    const result = await this.tableOrderModel.findOne({
      _id: tableOrderId,
      locationId,
    });

    return result.toObject();
  }

  async createOne(
    data: Omit<TableOrder, AutoGeneratedFields>,
  ): Promise<TableOrder> {
    const order = await this.tableOrderModel.create(data);
    return order.toObject();
  }

  async deleteOrderItems(
    tableOrderId: string,
    items: Partial<TableOrderItem>[],
  ): Promise<TableOrder> {
    const result = await this.tableOrderModel.findOneAndUpdate(
      { _id: tableOrderId },
      { $pullAll: { items } },
    );

    return result.toObject();
  }

  async updateOne(
    tableOrderId: string,
    data: Partial<TableOrder>,
  ): Promise<TableOrder> {
    const result = await this.tableOrderModel.findOneAndUpdate(
      { _id: tableOrderId },
      data,
    );

    return result.toObject();
  }
}
