import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { FilterQuery, Model } from 'mongoose';
import {
  CashRegister,
  CashRegisterDocument,
  CashRegisterPaymentSummary,
  CashRegisterStatus,
} from '../entities/cash-register';
import { buildOpenCashRegisterFilter } from '../utils/cash-register-open.utils';

export type ListCashRegistersFilters = {
  limit: number;
  offset: number;
  startedAtFrom?: Date;
  startedAtTo?: Date;
  finishedAtFrom?: Date;
  finishedAtTo?: Date;
};

export type CloseCashRegisterData = {
  finishedAt: Date;
  closedByUserId: string;
  closingAmount: number;
  expectedClosingAmount: number;
  difference: number;
  closingSummary: CashRegisterPaymentSummary;
};

interface ICashRegisterDataSource {
  createOne(
    data: Omit<CashRegister, AutoGeneratedFields>,
  ): Promise<CashRegister>;
  findById(id: string, organizationId: string): Promise<CashRegister | null>;
  findOpenByLocation(
    organizationId: string,
    locationId: string,
  ): Promise<CashRegister | null>;
  closeOne(
    id: string,
    organizationId: string,
    data: CloseCashRegisterData,
  ): Promise<boolean>;
  listByLocationAndFilters(
    organizationId: string,
    locationId: string,
    filters: ListCashRegistersFilters,
  ): Promise<{ cashRegisters: CashRegister[]; totalCount: number }>;
}

@Injectable()
export class CashRegisterDataSource implements ICashRegisterDataSource {
  constructor(
    @InjectModel(CashRegister.name)
    private cashRegisterModel: Model<CashRegisterDocument>,
  ) {}

  async createOne(
    data: Omit<CashRegister, AutoGeneratedFields>,
  ): Promise<CashRegister> {
    const cashRegister = await this.cashRegisterModel.create(data);
    return cashRegister.toObject();
  }

  async findById(
    id: string,
    organizationId: string,
  ): Promise<CashRegister | null> {
    const cashRegister = await this.cashRegisterModel.findOne({
      _id: id,
      organizationId,
    });

    return cashRegister?.toObject() ?? null;
  }

  async findOpenByLocation(
    organizationId: string,
    locationId: string,
  ): Promise<CashRegister | null> {
    const cashRegister = await this.cashRegisterModel.findOne(
      buildOpenCashRegisterFilter(organizationId, locationId),
    );

    return cashRegister?.toObject() ?? null;
  }

  async closeOne(
    id: string,
    organizationId: string,
    data: CloseCashRegisterData,
  ): Promise<boolean> {
    const result = await this.cashRegisterModel.updateOne(
      { _id: id, organizationId },
      {
        $set: {
          status: CashRegisterStatus.CLOSED,
          ...data,
        },
      },
    );

    return result.matchedCount > 0;
  }

  async listByLocationAndFilters(
    organizationId: string,
    locationId: string,
    filters: ListCashRegistersFilters,
  ): Promise<{ cashRegisters: CashRegister[]; totalCount: number }> {
    const query: FilterQuery<CashRegisterDocument> = {
      organizationId,
      locationId,
    };

    if (filters.startedAtFrom || filters.startedAtTo) {
      query.startedAt = {};
      if (filters.startedAtFrom) query.startedAt.$gte = filters.startedAtFrom;
      if (filters.startedAtTo) query.startedAt.$lte = filters.startedAtTo;
    }

    if (filters.finishedAtFrom || filters.finishedAtTo) {
      query.finishedAt = {};
      if (filters.finishedAtFrom) {
        query.finishedAt.$gte = filters.finishedAtFrom;
      }
      if (filters.finishedAtTo) {
        query.finishedAt.$lte = filters.finishedAtTo;
      }
    }

    const [cashRegisters, totalCount] = await Promise.all([
      this.cashRegisterModel
        .find(query, {}, { skip: filters.offset, limit: filters.limit })
        .sort({ startedAt: -1 }),
      this.cashRegisterModel.countDocuments(query),
    ]);

    return {
      cashRegisters: cashRegisters.map((cashRegister) =>
        cashRegister.toObject(),
      ),
      totalCount,
    };
  }
}
