import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { Model } from 'mongoose';
import {
  CashMovement,
  CashMovementDocument,
  CashMovementType,
} from '../entities/cash-movement';
import { roundToCents } from '../utils/cash-register-summary.utils';

interface ICashMovementDataSource {
  createOne(
    data: Omit<CashMovement, AutoGeneratedFields>,
  ): Promise<CashMovement>;
  listByCashRegister(
    cashRegisterId: string,
    organizationId: string,
    locationId: string,
  ): Promise<CashMovement[]>;
  sumByCashRegisterAndType(
    cashRegisterId: string,
    organizationId: string,
    locationId: string,
    type: CashMovementType,
  ): Promise<number>;
}

@Injectable()
export class CashMovementDataSource implements ICashMovementDataSource {
  constructor(
    @InjectModel(CashMovement.name)
    private cashMovementModel: Model<CashMovementDocument>,
  ) {}

  async createOne(
    data: Omit<CashMovement, AutoGeneratedFields>,
  ): Promise<CashMovement> {
    const movement = await this.cashMovementModel.create(data);
    return movement.toObject();
  }

  async listByCashRegister(
    cashRegisterId: string,
    organizationId: string,
    locationId: string,
  ): Promise<CashMovement[]> {
    const movements = await this.cashMovementModel
      .find({ cashRegisterId, organizationId, locationId })
      .sort({ createdAt: -1 });

    return movements.map((movement) => movement.toObject());
  }

  async sumByCashRegisterAndType(
    cashRegisterId: string,
    organizationId: string,
    locationId: string,
    type: CashMovementType,
  ): Promise<number> {
    const [result] = await this.cashMovementModel.aggregate([
      {
        $match: {
          organizationId,
          locationId,
          cashRegisterId,
          type,
        },
      },
      {
        $group: {
          _id: null,
          total: { $sum: '$amount' },
        },
      },
    ]);

    return roundToCents(result?.total ?? 0);
  }
}
