import { Menu } from '@modules/menu/entities/menu';
import { MenuTypes } from '@modules/menu/enums/menu-types';
import { Field, InputType } from '@nestjs/graphql';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { IsObjectId } from '@shared/validations/is-object-id';
import {
  IsArray,
  IsBoolean,
  IsEnum,
  IsOptional,
  IsString,
  Validate,
} from 'class-validator';

@InputType()
export class CreateMenuInput
  implements
    Omit<Menu, AutoGeneratedFields | 'categories' | 'categoryIds' | 'isActive'>
{
  organizationId: string;

  locationId: string;

  @IsArray()
  @IsEnum(MenuTypes, { each: true })
  @Field(() => [MenuTypes])
  type: MenuTypes[];

  @IsBoolean()
  @IsOptional()
  @Field({ nullable: true })
  isActive?: boolean;

  @Field()
  @IsString()
  name: string;

  @IsOptional()
  @IsString()
  @Field({ nullable: true })
  description?: string;

  @IsArray()
  @IsOptional()
  @Field(() => [String], { nullable: true })
  @Validate(IsObjectId, { each: true })
  categoryIds?: string[];
}
