import { Menu } from "@modules/menu/entities/menu";
import { Field, InputType } from "@nestjs/graphql";
import { AutoGeneratedFields } from "@shared/interfaces/auto-generated-fields";

@InputType()
export class CreateMenuInput implements Omit<Menu, AutoGeneratedFields> {
    organizationId: string;
  
    @Field()
    locationId: string
  
    @Field()
    isActive: boolean;
  
    @Field()
    name: string;
  
    @Field()
    description?: string;
  
    @Field( {nullable: true })
    categoryIds?: string[]
}