import { Menu } from '@modules/menu/entities/menu';
import { MenuTypes } from '@modules/menu/enums/menu-types';
import { Field, InputType } from '@nestjs/graphql';
import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { IsObjectId } from '@shared/validations/is-object-id';
import {
  IsArray,
  IsBoolean,
  IsEnum,
  IsOptional,
  IsString,
  Validate,
} from 'class-validator';

@InputType()
export class UpdateMenuInput
  implements Partial<Omit<Menu, AutoGeneratedFields | 'categories'>>
{
  organizationId: string;

  locationId: string;

  @Field()
  @Validate(IsObjectId)
  _id: string;

  @IsString()
  @IsOptional()
  @Field({ nullable: true })
  name?: string;

  @IsString()
  @IsOptional()
  @Field({ nullable: true })
  description?: string;

  @IsBoolean()
  @IsOptional()
  @Field({ nullable: true })
  isActive?: boolean;

  @IsArray()
  @IsEnum(MenuTypes, { each: true })
  @IsOptional()
  @Field(() => [MenuTypes], { nullable: true })
  types?: MenuTypes[];

  @IsArray()
  @IsOptional()
  @Field(() => [String], { nullable: true })
  @Validate(IsObjectId, { each: true })
  categoryIds?: string[];
}
