import { AutoGeneratedFields } from '@shared/interfaces/auto-generated-fields';
import { ProductImage, ProductImageDocument } from '../entities/product-image';
import { Injectable } from '@nestjs/common';
import { Model } from 'mongoose';
import { InjectModel } from '@nestjs/mongoose';

interface IProductImageDataSource {
  createOne(
    data: Omit<ProductImage, AutoGeneratedFields>,
  ): Promise<ProductImage>;
}

@Injectable()
export class ProductImageDataSource implements IProductImageDataSource {
  constructor(
    @InjectModel(ProductImage.name)
    private productImageModel: Model<ProductImageDocument>,
  ) {}

  async createOne(
    data: Omit<ProductImage, AutoGeneratedFields>,
  ): Promise<ProductImage> {
    const result = await this.productImageModel.create(data);
    return result.toObject();
  }
}
